# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8082
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
 
dubbo:
  application:
    name: service-consumer
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    #启动检查注册中心
    check: false
  consumer:
    #启动检查provider
    check: false
    #超时设置   默认1000  单位毫秒
    timeout: 5000
    #重试次数  默认0
    retries: 2